clear; clc;
% CASEA_A2_RUN_SERVICE_PENALTY_SWEEP
% A2: Fix "corner solutions" (u_ch -> 0) by increasing service-shortfall penalty.
%
% What we do:
%   - Sweep kappa_SF, a multiplicative factor applied to service penalty weights:
%       params.lambda_D, params.beta_D, params.lambda_W, params.beta_W
%     (waiting is proportional to deviation in sim_one_scenario, so scaling both
%      keeps consistency in the current model.)
%   - For each kappa_SF and each method variant (RN/RA × Full/Plain),
%     run optimization on DESIGN set (minibatch) and report metrics on TEST set (full-Ω).
%
% Outputs:
%   results/caseA_A2_*/caseA_A2_results.mat
%
% Notes:
%   - Requires cache/scenarios_design.mat and cache/scenarios_test.mat generated by Step1B.
%     If missing, falls back to cache/scenarios.mat (no hold-out).
%   - You can change kappa_sf_list to be more/less aggressive.
%
% Author: (auto-generated by ChatGPT)

root_dir = fileparts(mfilename('fullpath'));
addpath(root_dir);
addpath(fullfile(root_dir,'oracle'));
addpath(fullfile(root_dir,'utils'));

% ---------- load design/test scenarios ----------
cache_design = fullfile(root_dir,'cache','scenarios_design.mat');
cache_test   = fullfile(root_dir,'cache','scenarios_test.mat');
cache_all    = fullfile(root_dir,'cache','scenarios.mat');

use_split = exist(cache_design,'file')==2 && exist(cache_test,'file')==2;

if use_split
    Sd = load(cache_design,'scenarios_design');
    St = load(cache_test,'scenarios_test');
    scenarios_design = Sd.scenarios_design;
    scenarios_test   = St.scenarios_test;
else
    if exist(cache_all,'file')~=2
        error('No cached scenarios found. Run step1_prepare_scenarios (and step1b split if desired).');
    end
    S0 = load(cache_all,'scenarios');
    scenarios_design = S0.scenarios;
    scenarios_test   = S0.scenarios;
    warning('A2: no design/test split found. Using the same scenarios for design and test.');
end

SdN = numel(scenarios_design);
StN = numel(scenarios_test);

R   = scenarios_design(1).R;
dim = 2*R;
lb = 0.0; ub = 1.0;

% ---------- base oracle params ----------
params_opt_base  = oracle_make_params('eval.mode',"minibatch",'eval.B',30,'eval.K_resamp',1,'eval.seed',2025);
params_full_base = params_opt_base; params_full_base.eval.mode = "full";

% RN base (risk-neutral)
params_opt_RN_base  = apply_risk_neutral(params_opt_base);
params_full_RN_base = apply_risk_neutral(params_full_base);

% ---------- optimizer shared options ----------
opts_base = struct();
opts_base.num_particles = 30;
opts_base.max_iter      = 80;
opts_base.w_inertia     = 0.7;
opts_base.c1            = 1.5;
opts_base.c2            = 1.5;
opts_base.agent_dim     = 2;

% Kalman-pos
opts_base.Q_pos  = 1e-4;
opts_base.R_pos  = 1e-2;
opts_base.P0_pos = 1e-1;

% VA
opts_base.beta_va  = 0.85;
opts_base.gamma_va = 0.15;
opts_base.eps_va   = 1e-9;

% Kalman-fit (VA signal smoothing)
opts_base.Q_fit  = 1e-4;
opts_base.R_fit  = 5e-3;
opts_base.P0_fit = 1e-1;

opts_base.verbose = false;

% ---------- A2 sweep settings ----------
% kappa_SF scales service penalties (deviation + waiting) in both mean objective and CVaR loss.
kappa_sf_list = [1, 2, 5, 10, 20];     % <-- adjust if still cornered
seed_list     = 1001:1010;             % >=10 seeds recommended
nK = numel(kappa_sf_list);
nSeeds = numel(seed_list);

% ---------- method variants ----------
variants = { ...
    struct('name',"RA_Full",  'risk',"RA",'use_kalman_pos',true,'use_va',true,'use_kalman_fit',true), ...
    struct('name',"RN_Full",  'risk',"RN",'use_kalman_pos',true,'use_va',true,'use_kalman_fit',true), ...
    struct('name',"RA_Plain", 'risk',"RA",'use_kalman_pos',false,'use_va',false,'use_kalman_fit',false), ...
    struct('name',"RN_Plain", 'risk',"RN",'use_kalman_pos',false,'use_va',false,'use_kalman_fit',false) ...
};

% ---------- output directory ----------
out_dir = fullfile(root_dir,'results', ['caseA_A2_' datestr(now,'yyyymmdd_HHMMSS')]);
if ~exist(out_dir,'dir'), mkdir(out_dir); end

A2 = struct();
A2.kappa_sf_list = kappa_sf_list;
A2.seed_list     = seed_list;
A2.variants      = variants;
A2.R = R; A2.dim = dim;
A2.opts_base = opts_base;
A2.use_split = use_split;
A2.S_design  = SdN;
A2.S_test    = StN;
A2.data = cell(numel(variants), nK); % each: bestU, bestF_hist, out_test_full, params_snapshot

fprintf('\n=== Case A / A2: Service-penalty sweep (fix corner solutions) ===\n');
fprintf('Zones R=%d, dim=%d\n', R, dim);
fprintf('Design scenarios Sd=%d, Test scenarios St=%d\n', SdN, StN);
fprintf('kappa_SF: %s\n', mat2str(kappa_sf_list));
fprintf('seeds:    %s\n', mat2str(seed_list));

for kk = 1:nK
    kSF = kappa_sf_list(kk);

    % Build RA/RN params for this kSF (both opt and full-eval)
    [p_opt_RA,  p_full_RA] = apply_service_penalty_scale(params_opt_base,  params_full_base,  kSF);
    [p_opt_RN,  p_full_RN] = apply_service_penalty_scale(params_opt_RN_base, params_full_RN_base, kSF);

    fprintf('\n--- kappa_SF = %.3g ---\n', kSF);
    fprintf('  (lambda_D, beta_D, lambda_W, beta_W) scaled by %.3g\n', kSF);

    for v = 1:numel(variants)
        cfg = variants{v};
        name = cfg.name;
        fprintf('  Variant: %s\n', name);

        bestF_hist = nan(opts_base.max_iter, nSeeds);
        bestU      = nan(nSeeds, dim);
        out_test   = cell(nSeeds, 1);

        % choose risk params
        if cfg.risk == "RA"
            p_opt  = p_opt_RA;
            p_full = p_full_RA;
        else
            p_opt  = p_opt_RN;
            p_full = p_full_RN;
        end

        for sidx = 1:nSeeds
            seed = seed_list(sidx);
            rng(seed,'twister');

            optsv = opts_base;
            optsv.use_kalman_pos = cfg.use_kalman_pos;
            optsv.use_va         = cfg.use_va;
            optsv.use_kalman_fit = cfg.use_kalman_fit;

            [u, ~, hist] = pso_minimize_ma_kalman_va_oracle(scenarios_design, p_opt, dim, lb, ub, optsv);

            bestF_hist(:, sidx) = hist.best_F(:);
            bestU(sidx,:) = u;

            % Full-Ω evaluation on TEST set
            out = oracle_eval(u, scenarios_test, p_full, (1:StN).');
            out_test{sidx} = out;

            % fprintf('    seed=%d  test_fitness=%.6g  test_f1=%.6g  test_dev_mean=%.6g\n', ...
            %     seed, out.fitness, out.f1, mean(out.det.dev));
        end

        cell_data = struct();
        cell_data.kappa_SF   = kSF;
        cell_data.variant    = name;
        cell_data.bestF_hist = bestF_hist;
        cell_data.bestU      = bestU;
        cell_data.out_test   = out_test;
        cell_data.params_opt  = p_opt;
        cell_data.params_full = p_full;

        A2.data{v,kk} = cell_data;
    end
end

save(fullfile(out_dir,'caseA_A2_results.mat'), 'A2', '-v7.3');
fprintf('\n[Saved] %s\n', fullfile(out_dir,'caseA_A2_results.mat'));
fprintf('[Output dir] %s\n', out_dir);
